plugins {
    id 'io.spring.dependency-management'
}

dependencies {
    implementation project(':common')
    implementation project(':orders')
    implementation project(':payments')
    implementation project(':inventory')


    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'

    compileOnly "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
