dependencies {
    implementation project(':common')
    implementation project(':customers')
    implementation project(':catalog')
    implementation project(':inventory')
    implementation project(':branches')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    compileOnly "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"

    implementation "org.mapstruct:mapstruct:${rootProject.ext.mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${rootProject.ext.mapstructVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
