dependencies {
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework:spring-web'

    compileOnly "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
