dependencies {
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework:spring-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.fasterxml.jackson.core:jackson-annotations'

    compileOnly "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
    testCompileOnly "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
